### ISSUE TITLE
Operations to rewrite

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#1060]
Core:
- [x] `All` (w/ lift) PR #1061 - _Merged_
- [x] `Any` (w/ lift) PR #1062 - _Merged_
  - `Exist` and `IsEmpty` are built upon `Any`
- [x] `AsObservable` (w/ ~~OnSubscribe~~ lift) PR #1064 - _Merged_
- [x] `Buffer` (w/ lift) PR #1073 - _Merged_
  - size, time window, skip, observable boundary, observable start-end
- [x] `CombineLatest` (w/ OnSubscribe) PR #1079 - _Merged_
- [x] `Concat` (w/ ~~OnSubscribe~~ lift) PR #1074 - _Merged_
- [x] `Debounce` (w/ lift) PR #1094
  - time window, another observable
- [x] `DefaultIfEmpty` (w/ lift) PR #1080 - _Merged_
- [x] `Defer` (w/ OnSubscribe) PR #1081 - _Merged_
- [x] `Delay` (w/ ~~lift~~ keep as is) ~~PR #1093~~ PR #1144
  - `DelaySubscribe` (w/ OnSubscribe)
  - `DelayViaObservable` (w/ OnSubscribe)
- [x] `Dematerialize` (w/ lift) PR #1083 - _Merged_
- [x] `Distinct` (w/ lift) PR #1084 - _Merged_
  - regular, ~~custom equality comparator~~
- [x] `DistinctUntilChanged` (w/ lift) PR #1085 - _Merged_
- [x] `FinallyDo` (w/ lift) PR #1086 - _Merged_
- [x] `FlatMap` (w/ lift) -> rename to `MergeMap` PR #1087 - _Merged_
  - ~~regular~~, with iterator as sub-collection (`MergeMapIterable`)
- [x] `GroupByUntil` (w/ lift) PR #1095
- [x] `GroupJoin` (w/ OnSubscribe) PR #1096
- [x] `Interval` replace with `Timer` PR #1098
- [x] `Join` (w/ OnSubscribe) PR #1103
- [x] `MergeDelayError` (w/ lift) PR #1104
- [x] `MergeMaxConcurrent`(w/ lift) PR #1106
- [x] `Multicast` (w/ OnSubscribe); PR #1108
  - regular, factory+selector
- [x] `OnErrorResumeNextViaObservable` (w/ lift) PR #1109
- [x] `OnErrorReturn`(w/ lift) PR #1110
- [x] `OnExceptionResumeNextViaObservable` (w/ lift) PR #1117
- [x] `ParallelMerge` -> just rename PR #1118
- [x] `RefCount` (w/ OnSubscribe) PR #1119
- [x] `Replay` (w/ OnSubscribe) PR #1108
- [x] `Sample` (w/ lift)  PR #1098
  - time (state-sharing bug!), another Observable
- [x] `SequenceEquals` -> just rename PR #1120
- [x] `Skip` (w/ lift) into `OperatorSkipTimed` PR #1121
- [x] `SkipUntil` (w/ lift) PR #1122
- [x] `Switch` (w/ lift) PR #1130
- [x] `Take` (w/ lift) PR #1131
  - count: already present, time
- [x] `TakeLast` (w/ lift) PR #1134
  - count, time
- [x] `TakeUntil` (w/ lift) PR #1135
- [x] `TakeWhile` (w/ lift); remove indexed variant? PR #1115
- [x] `ThrottleFirst` (w/ lift) PR #1112
- [x] `TimeInterval` (w/ lift) PR #1111
- [x] `Timer` (w/ OnSubscribe)  PR #1098
- [x] `ToMap` (w/ OnSubscribe) PR #1099
- [x] `ToMultimap` (w/ OnSubscribe) PR #1097
- [x] `ToObservableFuture` (w/ OnSubscribe) PR #1088 - _Merged_
- [x] `Using` (w/ OnSubscribe) PR #1100
- [x] `Window` (w/ lift) PR ~~#1123~~, PR #1138
  - size, time window, skip, observable boundary, observable start-end

contrib-string
- [x] Optionally: refactor operators into separate classes. No changes.

contrib-async-util, PR #1101
- [x] `StartFuture` -> just rename
- [x] `OperationFromFunctionals.InvokeAsync` (w/ OnSubscribe)
- [x] `ForEachFuture` -> just rename
- [x] `DeferFuture` -> just rename

contrib-math, PR #1125
- [x] `Average` (w/ lift); ~~may keep current op-composition~~
  - int, long, float, double; w/ extractor function
- [x] `Min`, `MinBy`, `Max`, `MaxBy` ~~(w/ lift)~~; may keep current op-composition
- [x] `Sum` ~~(w/ lift)~~; may keep current op-composition

contrib-computation-expressions, PR #1129
- [x] `IfThen` (w/ OnSubscribe)
- [x] `SwitchCase` (w/ OnSubscribe)
- [x] `DoWhile`, `WhileDo` (w/ OnSubscribe)

contrib-joins
- [x] `When` (w/ OnSubscribe) PR #1126
