### ISSUE TITLE
2.0 progress on operators

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#3210]
This page tracks which operators have been implemented in the 2.x branch. New overloads and new operators proposed for 1.x or 2.x are not included.

  - [x] `amb` #3235
  - [x] `combineLatest` #3241
  - [x] `concat`
  - [x] `create`
  - [x] `defer`
  - [x] `empty`
  - [x] `error`
  - [x] `from` (iterable, array)
  - [x] `from` (plain future, i.e., not `CompletableFuture`)
  - [x] `interval`
  - [x] `just` (single)
  - [x] `just` (2-9 operands) ~~*I suggest deprecation/not implementing* -> fromArray instead~~ #3255 (to many tests depend on this, I don't want to change them all)
  - [x] `merge`
  - [x] `mergeDelayError`
  - [x] `never`
  - [x] `range` (unscheduled)
  - [x] `range` #3225 (scheduled) *I suggest deprecation/not implementing it* -> use composition
  - [x] `sequenceEqual` #3240
  - [x] `switchOnNext` #3234
  - [x] `timer` (once) ~~*implemented under the name interval(long, TimeUnit), may need name change*~~ #3223
  - [x] `using` #3242
  - [x] `zip` #3215
Instance methods
  - [x] `all`
  - [x] `autoConnect` (on `ConnectableObservable`)
  - [x] `ambWith` #3235
  - [x] `asObservable`
  - [x] `buffer` #3248 #3250
  - [x] `cache`
  - [x] `cast` #3223
  - [x] `collect` #3226
  - [x] `compose`
  - [x] `concatMap`
  - [x] `concatWith`
  - [x] `contains` #3223
  - [x] `count` *I suggest having only a single, long counter*
  - [x] `countLong` under the name count
  - [x] `debounce` #3254
  - [x] `defaultIfEmpty` #3230
  - [x] `delay` #3244
  - [x] `delaySubscription` #3244
  - [x] `dematerialize` #3243
  - [x] `distinct` #3224
  - [x] `distinctUntilChanged` #3224
  - [x] `doOnCompleted` #3225
  - [x] `doOnEach` #3225
  - [x] `doOnError` #3225
  - [x] `doOnNext` #3225
  - [x] `doOnRequest`
  - [x] `doOnSubscribe`
  - [x] `doOnTerminate` #3225
  - [x] `doOnUnsubscribe`
  - [x] `elementAt`
  - [x] `exists` #3223
  - [x] `filter`
  - [x] `finallyDo` #3225
  - [x] `first` (no predicate) #3232
  - [x] `first` (with predicate) #3232 *I suggest deprecating/not implementing this overload*
  - [x] `firstOrDefault` #3232 as an overload to first.
  - [x] `flatMap` (minus the paired version)
  - [x] `flatMap` (paired version) #3223
  - [x] `flatMap` (where onError and onCompleted is also mapped to an Observable) *I suggest dropping this*
  - [x] `flatMapIterable` #3223 *I'll come back to this if this can be implemented in a more efficient fashion*
  - [x] `forEach` (single consumer only)
  - [x] `forEach` (with error and completion callback)  *I suggest deprecating/not implementing this overload*
  - [x] `groupBy` #3212
  - [x] `groupJoin` *I suggest deprecating/not implementing this operator*
  - [x] `ignoreElements`
  - [x] `isEmpty`
  - [x] `join` *I suggest deprecating/not implementing this operator*
  - [x] `last` #3232 *I suggest dropping the predicate version*
  - [x] `lastOrDefault` #3232 *I suggest dropping the predicate version and having this as an overload under the name last*
  - [x] `lift`
  - [x] `limit` #3223 *I suggest dropping this and stick with take*
  - [x] `map`
  - [x] `materialize` #3243
  - [x] `mergeWith`
  - [x] `nest` #3224 *I suggest dropping this*
  - [x] `observeOn`
  - [x] `ofType` #3223
  - [x] `onBackpressureBlock` *this is already deprecated and I suggest dropping it*
  - [x] `onBackpressureBuffer` (without action)
  - [x] `onBackpressureBuffer` (with action) #3257
  - [x] `onBackpressureDrop`
  - [x] `onBackpressureLatest`
  - [x] `onErrorResumeNext` #3237
  - [x] `onErrorReturn` #3237
  - [x] `onExceptionResumeNext` #3237
  - [x] `publish`
  - [x] `reduce` ~~*still awaiting review/decision on the scan bug in #3171*~~ #3255
  - [x] `refCount` on `ConnectableObservable` #3246
  - [x] `repeat` (no scheduler)
  - [x] `repeat` (with scheduler) #3225 *I suggest dropping this overload* -> use composition
  - [x] `repeatWhen` #3238 *I'd like to implement this myself due to an elusive bug with retryWhen.*
  - [x] `replay`
  - [x] `retry` (except the indexed predicate which *I suggest dropping*
  - [x] `retryWhen` #3238 *I'd like to implement this myself due to an elusive bug in it*
  - [x] `sample` #3229
  - [x] `scan` ~~*still awaiting review/decision on the scan bug in #3171*~~ #3255
  - [x] `serialize` #3224
  - [x] `share` #3244
  - [x] `single` (no predicate)
  - [x] `single` (with predicate) *I suggest dropping this* -> use composition
  - [x] `singleOrDefault` (no predicate) as an overload to single
  - [x] `singleOrDefault` (with predicate) *I suggest dropping this* -> use composition
  - [x] `skip` (untimed)
  - [x] `skip` (timed) #3224
  - [x] `skipLast` (untimed)
  - [x] `skipLast` (timed) #3231
  - [x] `skipUntil`
  - [x] `skipWhile`
  - [x] `startWith`
  - [x] `subscribe`
  - [x] `subscribeOn`
  - [x] `switchIfEmpty` #3230
  - [x] `switchMap` #3234
  - [x] `take` (untimed)
  - [x] `take` (timed) #3224
  - [x] `takeLast` (untimed)
  - [x] `takeLast` (timed) #3231
  - [x] `takeLastBuffer` #3231
  - [x] `takeUntil`
  - [x] `takeWhile` #3239
  - [x] `throttleFirst` #3256
  - [x] `throttleLast` #3256
  - [x] `throttleWithTimeout` #3254
  - [x] `timeInterval` #3224
  - [x] `timeout` #3257
  - [x] `timestamp` #3223
  - [x] `toBlocking` #3245
  - [x] `toList`
  - [x] `toMap` *I suggest dropping this*
  - [x] `toMultimap` #3226 *I suggest dropping this*
  - [x] `toSingle` *This would require explicit dependency on 1.x or the complete implementation to be moved over to 2.x; a separate project would have been better...*
  - [x] `toSortedList`
  - [x] `unsafeSubscribe`
  - [x] `unsubscribeOn`
  - [x] `window` #3251, #3253, #3262
  - [x] `withLatestFrom` #3222
  - [x] `x` *lives on as a much simpler operator `to`*
  - [x] `zipWith` #3223

**Comment by akarnokd** [comment]
Operators I'm not going to implement:

  - `join`
  - `groupJoin`
  - `toSingle`
  - `just` 2-9 values
  - `forEach` with error + completion callbacks
  - `flatMap` that maps onError and onComplete notifications into some Observable as well.

**Comment by benjchristensen** [comment]
I understand join and groupJoin, but what is your reason for dismissing the others?

**Comment by akarnokd** [comment]
I don't feel the need to implement them but anybody else is welcome to do them.

**Comment by akarnokd** [comment]
All operators that I planned to implement are now implemented. Closing.
