### ISSUE TITLE
2.x: implementing the Reactive-Streams TCK tests

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4312]
It would be great if someone took the time and investigated how we could integrate and implement the Reactive-Streams TCK for our operators - which would make us the legitimate users of the "Reactive-Streams Compliant" label.
- [X] The TCK uses TestNG so one has to figure out how to run both JUnit and TestNG in the same gradle project. -> #4507
- [X] Implement the TCK for one operator. My understanding of the TCK is that you won't be able to implement it for some source and intermediate operators as the TCK expects some response patterns not always available. -> #4507
- [x] Implement the TCK for as many operators as possible. -> #4538

One drawback of the TCK that it is somewhat restrictive on error reporting on certain corner-cases we don't care about (like invalid request amount should call onError). For this case, I plan to implement an operator `tck()` that makes ensures the TCK receives what it expects.

For some reference, please look at the [RxJavaReactiveStreams](https://github.com/ReactiveX/RxJavaReactiveStreams) project.

**Comment by akarnokd** [comment]
Done!
