### ISSUE TITLE
2.x: Observable missing or incorrect images (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5319]
- [x] [Observable.singleOrError()](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#singleOrError()): There is no default value and an empty source should result in an error.
- [x] `Observable.combineLatestDelayError(ObservableSource[], Function)`: missing diagram
- [x] `Observable.combineLatestDelayError(Function, int, ObservableSource...)`: missing diagram
- [x] `Observable.concatArrayEager`: missing diagram
- [x] `Observable.error`: should include the X in the operator body indicating it as being the parameter/return value
- [x] `Observable.fromFuture`: the operator name in the box
- [x] `Observable.fromIterable`: the operator name in the box
- [x] `Observable.fromPublisher`: missing diagram
- [x] `Observable.just`: the element should be a parameter inside the box, such outside elements imply a subject type external push.
- [x] `Observable.just(T, T)` +7: optionally tailor the diagram to the actual number of arguments, plus move the constant values inside the box
- [x] `Observable.rangeLong`: the operator name in the box
- [x] `Observable.switchOnNextDelayError`: the operator name in the box, indicator of an error getting delayed
- [x] `Observable.zipArray`: indicate there is a function instead of implying the output is an array containing one element from each source.
- [x] `Observable.zipIterable`: the operator name in the box
- [x] `Observable.all`: example of a false result
- [x] `Observable.ambWith`: the operator name in the box
- [x] `Observable.blockingFirst`: missing diagram
- [x] `Observable.blockingForEach`: the operator name in the box
- [x] `Observable.blockingIterable`: the operator name in the box, indicate that blocking may happen for each element
- [x] `Observable.blockingLast`: the operator name in the box
- [x] `Observable.blockingLast(T)`: the operator name in the box, indicate default in the box, fix labels
- [x] `Observable.blockingLatest`: missing diagram
- [x] `Observable.blockingMostRecent`: the operator name in the box
- [x] `Observable.blockingNext`: the operator name in the box
- [x] `Observable.blockingSingle`: the operator name in the box
- [x] `Observable.blockingSingle(T)`: the operator name in the box, indicate default in the box, fix labels
- [x] `Observable.toFuture()`: the operator name in the box, indicate multi-value, empty and error behavior
- [x] `Observable.blockingSubscribe`: missing diagram
- [x] `Observable.cacheWithInitialCapacity`: the operator name in the box
- [x] `Observable.collectInto`: the operator name in the box, indicate the shared collection
- [x] `Observable.concatMapCompletable`: missing diagram
- [x] `Observable.concatMapDelayError`: missing diagram
- [x] `Observable.concatMapEager`: missing diagram
- [x] `Observable.concatMapEagerDelayError`: missing diagram
- [x] `Observable.concatMapIterable`: missing diagram
- [x] `Observable.doAfterNext`: missing diagram
- [x] `Observable.doFinally`: missing diagram
- [x] `Observable.doOnDispose`: the operator name in the box
- [x] `Observable.doOnComplete`: indicate that the events pass through and the star is execute before the onComplete to downstream
- [x] `Observable.doOnError`: indicate that the events pass through and the star is execute before the onError to downstream
- [x] `Observable.doOnLifecycle`: change unsubscribe to dispose
- [x] `Observable.doOnNext`: indicate that the events pass through and the star is execute before the onNext to downstream
- [x] `Observable.doOnTerminate`: indicate that the events pass through and the star is execute before the onError or onComplete to downstream
- [x] `Observable.elementAt(long)`: example of empty source
- [x] `Observable.elementAt(long, T)`: example of empty source
- [x] `Observable.elementAtOrError(long)`: example of empty source
- [x] `Observable.firstElement`: diagram is stretched
- [x] `Observable.firstOrError`: the operator name in the box
- [x] `Observable.flatMap(Function, boolean, int)`: missing diagram
- [x] `Observable.flatMap(Function, boolean, int, int)`: missing diagram
- [x] `Observable.flatMap(Function, Function, Callable, int)`: missing diagram
- [x] `Observable.flatMap(Function, int)`: missing diagram
- [x] `Observable.flatMap(Function, BiFunction, boolean, int)`: missing diagram
- [x] `Observable.flatMap(Function, BiFunction, boolean, int, int)`: missing diagram
- [x] `Observable.flatMap(Function, BiFunction, int)`: missing diagram
- [x] `Observable.flatMapCompletable()`: missing diagram
- [x] `Observable.flatMapIterable(Function)`: diagram looks stretched
- [x] `Observable.forEach()`: missing diagram
- [x] `Observable.forEachWhile()`: missing diagram
- [x] `Observable.hide()`: missing diagram - not sure how to represent this
- [x] `Observable.lastOrError()`: operator name in the box, error case example.
- [x] `Observable.onErrorReturn()`: indicate that the value is the result of a function call
- [x] `Observable.onErrorReturnItem()`: operator name in the box
- [x] `Observable.onTerminateDetach`: missing diagram
- [x] `Observable.publish(Function)`: there is no connect call, may need extensive redrawing
- [x] `Observable.reduceWith()`: operator name in the box
- [x] `Observable.repeat()` + overloads: indicate fresh subscriptions happen, not caching
- [x] `Observable.repeatUntil`: operator name in the box, indicate fresh subscriptions
- [x] `Observable.replay()` + overloads: remove publish
- [x] `Observable.replay(Function, ...)` overloads: may need extensive redrawing
- [x] `Observable.retry(long)` indicate limited retry effect
- [x] `Observable.retry(Predicate)` indicate predicate effect, show it in the box
- [x] `Observable.retry(long, Predicate)` indicate predicate, show them in the box
- [x] `Observable.retryUntil`: operator name in the box, show BooleanSupplier
- [x] `Observable.share()`: fix labels with unsubscribe
- [x] `Observable.singleElement`: example with empty source
- [x] `Observable.sorted`: missing diagram
- [x] `Observable.startWith(T)`: have a single item as start value
- [x] `Observable.startWithArray(T...)`: operator name
- [x] `Observable.subscribe` + overloads: missing diagram
- [x] [Observable.switchMapSingle](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#switchMapSingle(io.reactivex.functions.Function)): inner sources should have 1 item.
- [x] `Observable.switchMapDelayError` + indicate the error case
- [x] `Observable.toList(Callable)`: indicate the custom collection somehow?
- [x] `Observable.toFlowable()`: missing diagram
- [x] `Observable.unsubscribeOn()`: missing diagram
- [x] `Observable.zipWith()` + overloads: the diagram is in line with some text and appears pushed to the right
- [x] `Observable.test()`: missing diagram, can this be represented as diagram?

**Comment by akarnokd** [comment]
PRs welcome. The most easy ones are those that require alignment/displayed size corrections.

**Comment by digitalbuddha** [comment]
Hi David, I'd love to help, what would I use to edit the diagrams?

**Comment by akarnokd** [comment]
If you are on Mac and you own OmniGraffle, there is a file for **all** traditional diagrams:
https://github.com/ReactiveX/reactivex.github.io/issues/223

I'm using Excel 2007+ on Windows to draw the newer diagrams and have a file [here](https://drive.google.com/open?id=0B4T7ZW3brESKQV9KaEF5YnpjM0k) you can use as basis for newer diagrams. I don't know if the open office variants could open this file or not, Google's viewer certainly doesn't show the drawings.

I suppose as a last resort you can draw in the open-office variants as well and post the PNGs in this issue. Uploading it requires access to the wiki git of RxJava. The target rendering is 640 pixels wide and as long as it needs to be.

The process is as follows:

- Draw diagram(s)
- Upload to git
- Modify Javadoc locally to point to the raw usercontent
- Verify and fix alignment/stretching
- Commit PR to RxJava itself

**Comment by wbinarytree** [comment]
Is it `switchMapSingle` need a new diagram too? SingleResource can't emit 2 items.

**Comment by akarnokd** [comment]
Yes. I'll add it to the list above.

**Comment by akarnokd** [comment]
## ConcatArrayEager

![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatArrayEager.png)

**Comment by akarnokd** [comment]
## Error

![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/error.item.png)
![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/error.supplier.png)

**Comment by akarnokd** [comment]
## fromFuture

![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromFuture.noarg.png)
![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromFuture.timeout.png)
![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromFuture.scheduler.png)
![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromFuture.timeout.scheduler.png)

**Comment by akarnokd** [comment]
## fromIterable

![Image](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromIterable.png)

**Comment by davidmoten** [comment]
Another option is to use free open-source multi-platform Inkscape. Templates here:

https://github.com/davidmoten/rxjava-marble-template

**Comment by leonardortlima** [comment]
**startWith(T)**

![startwith t](https://user-images.githubusercontent.com/6715387/28749559-b5f451dc-74a1-11e7-9a24-db339a2da754.png)

**Comment by leonardortlima** [comment]
**startWithArray(T...)**

![startwitharray](https://user-images.githubusercontent.com/6715387/28749281-5f23f834-7498-11e7-99a5-49033842ecb9.png)

**Comment by akarnokd** [comment]
Thanks. Could you make sure the operator box has its contents centered?

**Comment by leonardortlima** [comment]
Sure. Going to edit them.

**Comment by leonardortlima** [comment]
**sorted()**

Is it okay to add numbers to the marbles?

![sorted](https://user-images.githubusercontent.com/6715387/28749679-1660f5b2-74a6-11e7-909b-f9c6cb7ce2c5.png)

**Comment by akarnokd** [comment]
In this case yes, because it also demonstrates the self-comparable nature required (changing the order of colors is unlikely to convey the sorting aspect). For most of the other operators, the matching up of the color should be enough.

**Comment by akarnokd** [comment]
Not sure how you do these images, could you add shadows to the marbles, the time arrows and the vertical complete indicators?

**Comment by leonardortlima** [comment]
I'm using @davidmoten's template. Going to edit them to add the shadows.

**Comment by akarnokd** [comment]
sorted(): it would be better that the source marbles are at the beginning and the output is only happening after onComplete:

```
---5--3--1--4--2--|--------------
[            sorted()           ]
---------------------1-2-3-4-5-|-
```

**Comment by leonardortlima** [comment]
Added shadows and edited the `sorted()` operator.

**Comment by leonardortlima** [comment]
**just(T)**

![just](https://user-images.githubusercontent.com/6715387/28749794-944aea34-74a9-11e7-9e52-43604442c87d.png)

**Comment by leonardortlima** [comment]
**rangelong()**

![rangelong](https://user-images.githubusercontent.com/6715387/28749798-cf44b69c-74a9-11e7-853b-958018e492c4.png)

**Comment by akarnokd** [comment]
Thanks @leonardortlima ! The first 5 images is added via #5524.

**Comment by cardamon** [comment]
Just noticed that `Single.filter` and `Maybe.filter` are also incorrect; they seem to be copied from `Observable.filter`.

**Comment by akarnokd** [comment]
Quite possibly the other base reactive classes have copy-paste diagrams. This issue tracks the fixes of `Observable` but if you want, I can open issues for the other classes individually.

**Comment by akarnokd** [comment]
![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.2.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.3.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.4.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.5.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.6.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.7.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.8.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.9.png)

![just(2)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/just.10.png)

![switchOnNextDelayError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/switchOnNextDelayError.png)

**Comment by akarnokd** [comment]
From #5668:

![singleelement](https://user-images.githubusercontent.com/4089934/31583261-a6da996a-b18f-11e7-8682-dffa647c7e4a.png)

**Comment by akarnokd** [comment]
### zipIterable

![zipIterable](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/zipIterable.o.png)

### ambWith

![ambWith](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/ambWith.o.png)

### blockingForEach

![blockingForEach](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingForEach.o.png)

### blockingIterable

![blockingIterable](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingIterable.o.png)

### blockingLast

![blockingLast](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingLast.o.png)

![blockingLast](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingLastDefault.o.png)

### blockingMostRecent

![blockingMostRecent](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingMostRecent.o.png)

### blockingNext

![blockingNext](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingNext.o.png)

### blockingSingle

![blockingSingle](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingSingle.o.png)

![blockingSingle](https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/blockingSingleDefault.o.png)

### cacheWithInitialCapacity

![cachecWithInitialCapacity](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/cacheWithInitialCapacity.o.png)

**Comment by akarnokd** [comment]
### all

![cachecWithInitialCapacity](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/all.o.png)

### fromPublisher

![cachecWithInitialCapacity](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/fromPublisher.o.png)

### zipArray

![cachecWithInitialCapacity](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/zipArray.o.png)

**Comment by akarnokd** [comment]
### blockingFirst

![blockingFirst](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingFirst.o.png)


![blockingFirst](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingFirst.o.default.png)

### toFuture


![toFuture](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFuture.o.png)


### blockingSubscribe

![blockingSubscribe](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingSubscribe.o.0.png)

![blockingSubscribe](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingSubscribe.o.1.png)

![blockingSubscribe](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingSubscribe.o.2.png)

![blockingSubscribe](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/blockingSubscribe.o.png)

### collectInto

![collectInto](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/collectInto.o.png)

### doOnComplete

![doOnComplete](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doOnComplete.o.png)

### doOnError

![doOnError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doOnError.o.png)

### doOnLifecycle

![doOnLifecycle](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doOnLifecycle.o.png)

### doOnNext

![doOnNext](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doOnNext.o.png)

**Comment by akarnokd** [comment]
### concatMapCompletable

![concatMapCompletable](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatMapCompletable.o.png)

### concatMapDelayError

![concatMapDelayError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatMapDelayError.o.png)

### concatMapEager

![concatMapEager](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatMapEager.o.png)

### concatMapEagerDelayError

![concatMapEagerDelayError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatMapEagerDelayError.o.png)

### concatMapIterable

![concatMapIterable](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/concatMapIterable.o.png)

### doAfterNext

![doAfterNext](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doAfterNext.o.png)

### doFinally

![doFinally](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doFinally.o.png)

**Comment by akarnokd** [comment]
### doOnTerminate

![doOnTerminate](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/doOnTerminate.o.png)

### elementAt

![elementAt](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/elementAt.o.png)
![elementAt](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/elementAtDefault.o.png)

### elementAtOrError

![elementAtOrError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/elementAtOrError.o.png)

### firstOrError

![firstOrError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/firstOrError.o.png)

### flatMap

![flatMap](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/flatMapDelayError.o.png)
![flatMap](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/flatMapMaxConcurrency.o.png)

**Comment by akarnokd** [comment]
![flatMapCompletable](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/flatMapCompletable.o.png)

![flatMapCompletable](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/flatMapCompletableDelayError.o.png)

![forEach](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/forEach.o.png)

![forEachWhile](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/forEachWhile.o.png)

![hide](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/hide.o.png)

**Comment by akarnokd** [comment]
![lastOrError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/lastOrError.png)
![onErrorReturn](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/onErrorReturn.o.png)
![onErrorReturnItem](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/onErrorReturnItem.o.png)
![onTerminateDetach](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/onTerminateDetach.o.png)
![publish(Function)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/publishFunction.o.png)
![reduce(seed, f)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/reduceSeed.o.png)
![reduceWith](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/reduceWith.o.png)
![repeat()](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/repeatInf.o.png)
![repeat(long)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/repeatCount.o.png)
![repeatUntil](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/repeatUntil.o.png)
![replay()](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.png)
![replay(int)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.n.png)  
![replay(int, long, TimeUnit)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.nt.png)
![replay(int, long, TimeUnit, Scheduler)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.nts.png)
![replay(int, Scheduler)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.ns.png)
![replay(long, TimeUnit)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.t.png)
![replay(long, TimeUnit, Scheduler)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.ts.png)
![replay(Scheduler)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.s.png)

**Comment by akarnokd** [comment]
![no arguments](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.f.png)
![scheduler](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fs.png)
![bufferSize](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fn.png)
![bufferSize, scheduler](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fns.png)
![time](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.ft.png)
![time, scheduler](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fts.png)
![bufferSize, time](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fnt.png)
![bufferSize, time, scheduler](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/replay.o.fnts.png)

**Comment by akarnokd** [comment]
![retry(int)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retry.o.n.png)
![retry(BiFunction)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retry.o.ne.png)
![retry(Predicate)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retry.o.e.png)
![retry(int, Predicate)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retry.o.nfe.png)
![retryUntil(BooleanSupplier)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retryUntil.o.png)
![share](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/publishRefCount.o.png)
![switchMapSingle](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/switchMapSingle.o.png)
![switchMapSingleDelayError](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/switchMapSingleDelayError.o.png)

**Comment by akarnokd** [comment]
![toList(Callable)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toList.o.c.png)
![toFlowable(BUFFER)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFlowable.o.buffer.png)
![toFlowable(DROP)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFlowable.o.drop.png)
![toFlowable(LATEST)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFlowable.o.latest.png)
![toFlowable(ERROR)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFlowable.o.error.png)
![toFlowable(MISSING)](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toFlowable.o.missing.png)
![unsubscribeOn](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/unsubscribeOn.o.png)
