### ISSUE TITLE
2.x: Completable missing or incorrect marbles (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5789]
- [x] `ambArray`: missing diagram
- [x] `amb`: missing diagram
- [x] `complete`: missing diagram
- [x] `concatArray`: missing diagram
- [x] `concat`: missing diagram
- [x] `create`: missing diaglam
- [x] `unsafeCreate`: missing diagram
- [x] `defer`: missing diagram
- [x] `error`: missing diagram
- [x] `fromAction`: missing diagram
- [x] `fromCallable`: missing diagram
- [x] `fromFuture`: missing diagram
- [x] `fromObservable`: missing diagram
- [x] `fromPublisher`: missing diagram
- [x] `fromRunnable`: missing diagram
- [x] `fromSingle`: missing diagram
- [x] `mergeArray`: missing diagram
- [x] `merge`: missing diagram
- [x] `mergeArrayDelayError`: missing diagram
- [x] `mergeDelayError`: missing diagram
- [x] `never`: missing diagram
- [x] `timer`: missing diagram
- [x] `using`: missing diagram
- [x] `wrap`: missing diagram
- [x] `ambWith`: missing diagram
- [x] `andThen`: missing diagram
- [x] `as`: missing diagram
- [x] `blockingAwait`: missing diagram
- [x] `blockingGet`: missing diagram
- [x] `cache`: missing diagram
- [x] `compose`: missing diagram
- [x] `concatWith`: missing diagram
- [x] `delay`: missing diagram
- [x] `doOnComplete`: missing diagram
- [x] `doOnDispose`: missing diagram
- [x] `doOnError`: missing diagram
- [x] `doOnEvent`: missing diagram
- [x] `doOnLifecycle`: missing diagram
- [x] `doOnSubscribe`: missing diagram
- [x] `doOnTerminate`: missing diagram
- [x] `doAfterTerminate`: missing diagram
- [x] `doFinally`: missing diagram
- [x] `lift`: missing diagram
- [x] `mergeWith`: missing diagram
- [x] `observeOn`: missing diagram
- [x] `onErrorComplete`: missing diagram
- [x] `onErrorResumeNext`: missing diagram
- [x] `onTerminateDetach`: missing diagram
- [x] `repeat`: missing diagram
- [x] `repeatUntil`: missing diagram
- [x] `repeatWhen`: missing diagram
- [x] `retry`: missing diagram
- [x] `retryWhen`: missing diagram
- [x] `startWith`: missing diagram
- [x] `hide`: missing diagram
- [x] `subscribe`: missing diagram
- [x] `subscribeWith`: missing diagram?
- [x] `subscribeOn`: missing diagram
- [x] `timeout`: missing diagram
- [x] `to`: missing diagram
- [x] `toFlowable`: missing diagram
- [x] `toMaybe`: wrong operator name in box
- [x] `toObservable`: use the old diagram of `toMaybe`
- [x] `toSingle`: missing diagram
- [x] `toSingleDefault`: missing diagram
- [x] `unsubscribeOn`: missing diagram
- [x] `test`: missing diagram

**Comment by akarnokd** [comment]
Done.
