### ISSUE TITLE
3.x: Maybe incorrect or missing marbles (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5806]
- [x] `amb`: missing diagram
- [x] `ambArray`: missing diagram
- [x] `concat(Iterable)`: missing diagram
- [x] `concat(Publisher)`: missing diagram
- [x] `concat(Publisher, int)`: missing diagram
- [x] `concatArray`: missing diagram
- [x] `concatArrayDelayError`: indicate error delayed, 1 marble per source
- [x] `concatArrayEager`: missing diagram
- [x] `concatDelayError(Iterable)`: missing diagram
- [x] `concatDelayError(Publisher)`: missing diagram
- [x] `concatDelayError(Publisher, int)`: fix overlap/misalignment inside the operator box
- [x] `concatEager(Iterable)`: missing diagram
- [x] `concatEager(Publisher)`: missing diagram
- [x] `create`: missing diagram
- [x] `defer`: missing diagram
- [x] `error(Callable)`: indicate callable returns the error
- [x] `fromAction`: missing diagram
- [x] `fromCompletable`: missing diagram
- [x] `fromSingle`: missing diagram
- [x] `fromCallable`: missing diagram
- [x] `fromFuture(Future)`: operator name in the box, indicate Future is the parameter
- [x] `fromFuture(Future, long, TimeUnit)`: operator name in the box, indicate Future is the parameter, indicate timeout
- [x] `fromRunnable`: missing diagram
- [x] `merge(Iterable)`: missing diagram
- [x] `merge(Publisher)`: missing diagram
- [x] `merge(Publisher, int)`: missing diagram
- [x] `mergeArray`: missing diagram
- [x] `mergeArrayDelayError`: one marble per Maybe source
- [x] `mergeDelayError(Iterable)`: one marble per Maybe source
- [x] `mergeDelayError(Publisher)`: one marble per Maybe source
- [x] `mergeDelayError(Maybe, Maybe, ...)`: one marble per Maybe source
- [x] `sequenceEqual` + 1: result should be `Single`.
- [x] `timer` + 1: result should be Maybe
- [x] `using` + 1: rework to indicate the created Maybe
- [x] `wrap`: missing marble
- [x] `zip(Iterable)`: one marble per Maybe source, result should be Maybe
- [x] `zip(Maybe, Maybe, ...)` + 8: one marble per Maybe source, result should be Maybe
- [x] `zipArray`: one marble per Maybe source, result should be Maybe
- [x] `ambWith`: one marble per Maybe source, result should be Maybe
- [x] ~~`as`: missing diagram~~ operator removed
- [x] `blockingGet` + 1: missing diagram
- [x] `cache`: one marble per Maybe source, result should be Maybe
- [x] `cast`: missing diagram
- [x] `compose`: missing diagram
- [x] `concatMap`: indicate Maybe target, indicate empty source
- [x] `concatWith`: one marble per Maybe source, result should be Maybe, operator name, indicate other is a parameter
- [x] `contains`: one marble per Maybe source, result should be Single, empty case
- [x] `count`: one marble per maybe, operator name, result should be Single, empty case
- [x] `defaultIfEmpty`: non-empty case, result should be Maybe
- [x] `delay(time)` + 3: one marble per Maybe source, result should be Maybe
- [x] `delay(Publisher)`: one marble per Maybe, one signal by the Publisher, empty publisher case
- [x] `delaySubscription(Publisher)`: missing diagram
- [x] `delaySubscription(time)` + 1: one marble per Maybe source, result should be Maybe
- [x] `doAfterSuccess`: missing diagram
- [x] `doAfterTerminate`: operator name, one marble per Maybe, result should be Maybe
- [x] `doFinally`: missing diagram
- [x] `doOnDispose`: missing diagram
- [x] `doOnComplete`: one marble per Maybe, result should be Maybe
- [x] `doOnError`: missing diagram
- [x] `doOnEvent`: missing diagram
- [x] `doOnSubscribe`: missing diagram
- [x] `doOnSuccess`: missing diagram
- [x] `doOnTerminate`: one marble per Maybe, result should be Maybe
- [x] `filter`: one marble per Maybe, result should be Maybe
- [x] `flatMap(Function, Function, Callable)`: one marble per Maybe, result should be Maybe
- [x] `flatMap(Function, BiFunction)`: one marble per Maybe, result should be Maybe
- [x] `flatMapObservable`: should be mapped into an Observable
- [x] `flatMapPublisher`: indicate backpressure
- [x] `flatMapSingle`: indicate empty maybe results in error
- [x] `flatMapSingleElement`: operator name, indicate empty maybe
- [x] `flatMapCompletable`: indicate empty maybe
- [x] `hide`: missing diagram
- [x] `ignoreElement`: operator name, one marble per Maybe, result should be Maybe
- [x] `isEmpty`: result should be Single
- [x] `mergeWith`: operator name, one marble per Maybe, indicate backpressure
- [x] `ofType`: one marble per Maybe
- [x] `onErrorComplete` + 1: missing diagram
- [x] `onErrorResumeNext`: one marble per Maybe, result should be Maybe
- [x] `onErrorResumeWith`: one marble per Maybe, result should be Maybe
- [x] `onErrorReturn`: one marble per Maybe, result should be Maybe, indicate callback
- [x] `onErrorReturnItem`: operator name, one marble per Maybe, result should be Maybe, indicate normal outcome
- [x] ~~`onExceptionResumeNext`: operator takes a Maybe source directlyˇ~~ operator removed
- [x] `onTerminateDetach`: missing diagram
- [x] `repeat` + 1: one marble per source, indicate backpressure, indicate repeat conditions
- [x] `repeatUntil`: operator name, repeat condition, indicate backpressure
- [x] `repeatWhen`: one marble per Maybe, indicate backpressure
- [x] `retry` + 2: one marble per Maybe, result should be Maybe, indicate repeat conditions
- [x] `retry(int, Predicate)`: missing diagram
- [x] `retry(Predicate)`: missing diagram
- [x] `retryUntil`: missing diagram
- [x] `retryWhen`: one marble per Maybe, output should be Maybe
- [x] `switchIfEmpty` + 1: improve diagrams, indicate argument type
- [x] `takeUntil` + 1: one marble per Maybe, output should be Maybe
- [x] `timeout` + 3: one marble per Maybe, output should be Maybe
- [x] `timeout(MaybeSource)`: missing diagram
- [x] `timeout(MaybeSource, MaybeSource)`: missing diagram
- [x] `timeout(Publisher)`: missing diagram
- [x] `timeout(Publisher, MaybeSource)`: missing diagram
- [x] `to`: missing diagram
- [x] `toFlowable`: missing diagram
- [x] `toObservable`: missing diagram
- [x] `toSingle` + 1: missing diagram
- [x] `unsubscribeOn`: missing diagram
- [x] `zipWith`: one marble per Maybe, output should be Maybe

**Comment by akarnokd** [comment]
Here is the Excel file I draw the diagrams in: https://drive.google.com/file/d/1di67kFJEuiLPyq14JlnV3vFl-muaCMfH/view?usp=sharing

**Comment by ourtutorial** [comment]
Here is an diagram issue
