### ISSUE TITLE
4.x: Flowable missing or incorrect marbles (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5813]
- [x] `amb`: indicate cancellation and request propagation
- [x] `ambArray`: indicate cancellation and request propagation
- [ ] `combineLatest` + 4: missing diagram
- [ ] `combineLatestDelayError` + 5: missing diagram
- [ ] `concatArrayDelayError`: operator name, indicate error delayed
- [x] `concatArrayEager` + 1: missing diagram
- [x] `concatArrayEagerDelayError` + 1: missing diagram
- [ ] `concatDelayError` + 2: missing diagram
- [x] `concatEager` + 4: missing diagram
- [ ] `concatEagerDelayError` + 4: missing diagram
- [ ] `create`: missing diagram
- [ ] `error(Callable)`: indicate callback that creates the Throwable
- [ ] `error(Throwable): indicate parameter
- [ ] `fromArray`: operator name, indicate items inside the box
- [ ] `fromCallable`: indicate item is the result of the callback inside the box
- [ ] `fromFuture` + 3: operator name
- [ ] `fromIterable`: operator name, indicate items inside the box
- [ ] `fromPublisher`: missing diagram
- [ ] `generate` + 4: missing diagram
- [ ] `intervalRange` + 1: missing diagram
- [ ] `just` + 8: indicate item inside the box (as many as there are sources, so 1..9)
- [ ] `mergeArray` + 1: operator name
- [ ] `mergeArrayDelayError` + 1: operator name
- [ ] `mergeDelayError` + 1: indicate inner sources are generated
- [ ] `sequenceEqual` + 3: indicate cancellation after the mismatch has been found
- [ ] `switchOnNextDelayError` + 1: operator name, indicate error delay
- [ ] `using` + 1: indicate actual Flowable and items
- [ ] `zipArray`: operator name
- [ ] `zipIterable`: operator name
- [ ] `all`: should return Single
- [x] `ambWith`: indicate cancellation and request propagation
- [ ] `exists`: should return Single
- [x] ~~`as`: missing diagram~~: operator removed
- [ ] `blockingFirst` + 1: missing diagram
- [ ] `blockingForEach`: operator name
- [ ] `blockingIterable` + 1: operator name, indicate iterator call to `hasNext()` and `next()`
- [ ] `blockingLast` + 1: operator name
- [ ] `blockingLatest`: missing diagram
- [ ] `blockingMostRecent`: operator name
- [ ] `blockingNext`: operator name
- [ ] `blockingSingle` + 1: operator name
- [x] `toFuture`: rework diagram to indicate `Future`
- [ ] `blockingSubscribe` + 4: missing diagram
- [ ] `buffer(..., Callable)` + 6: indicate custom collection
- [ ] `buffer(open, close)` + 1: parameter name in the box
- [ ] `collect`: indicate initial container supplier, should return Single
- [ ] `collectInto`: indicate initial container, should return Single, operator name
- [ ] `compose`: missing diagram
- [ ] `concatMap(prefetch)`: indicate prefetch effects through requests
- [ ] `concatMapDelayError` + 1: missing diagram
- [ ] `concatMapEager` + 1: missing diagram
- [ ] `concatMapEagerDelayError` + 1: missing diagram
- [ ] `concatMapIterable` + 1: missing diagram
- [ ] `concatWith`: operator name
- [ ] `contains`: should return Single
- [ ] `count`: operator name
- [ ] `defaultIfEmpty`: indicate non-empty case
- [ ] `delaySubscription(Publisher)`: missing diagram
- [ ] `dematerialize`: indicate dematerializing a terminal notification cancels the source
- [ ] `doFinally`: missing diagram
- [ ] `doAfterNext`: missing diagram
- [ ] `doOnCancel`: operator name, unsubscribe -> cancel in text
- [ ] `doOnComplete`: indicate events pass through
- [ ] `doOnEach` + 1: indicate events pass through
- [ ] `doOnError`: indicate events pass through
- [ ] `doOnNext`: indicate events pass through
- [ ] `doOnRequest`: missing diagram
- [ ] `doOnTerminate`: indicate events pass through, show both error and complete case
- [ ] `elementAt`: should return Maybe, indicate if source is shorter than index
- [ ] `elementAtOrDefault`: should return Single, indicate if source has that element
- [ ] `elementAtOrError`: should return Single, indicate error case
- [ ] `firstElement`: image aspect off, add case separator dashed vertical line
- [x] `first`: image aspect off
- [ ] `firstOrError`: combine two sections, vertical separator, empty source arrow
- [ ] `flatMap(..., delayError)`: indicate error delay case
- [ ] `flatMap(..., maxConcurrency)` + 2: missing diagram
- [ ] `flatMap(Function, Function, Callable, int)`: missing diagram
- [ ] `flatMap(Function, BiFunction, boolean, int)` + 1: missing diagram
- [ ] `flatMap(Function, BiFunction, int)`: missing diagram
- [ ] `flatMapCompletable` + 1: missing diagram
- [ ] `flatMapIterable` + 1: image aspect looks off
- [ ] `flatMapMaybe` + 1: missing diagram
- [ ] `flatMapSingle` + 1: missing diagram
- [ ] `forEach`: missing diagram
- [ ] `forEachWhile` + 2: missing diagram
- [ ] `hide`: missing diagram
- [ ] `isEmpty`: should return Single
- [ ] `lastElement`: operator name, should return Maybe
- [ ] `last(T)`: should return Single, operator name
- [ ] `lastOrError`: combine sections into one, add vertical case separator
- [x] `limit`: ~~missing diagram~~ operator renamed to `take`
- [ ] `mergeWith`: operator name, indicate the second source as parameter
- [x] `onErrorResumeNext(Function)`: indicate error function
- [ ] `onErrorReturn`: indicate error function
- [ ] `onErrorReturnItem`: operator name
- [ ] `onTerminateDetach`: missing diagram
- [ ] `publish(Function)` + 1: rework diagram
- [ ] `rebatchRequests`: missing diagram
- [ ] `reduce(seed, ...)`: indicate star as parameter
- [ ] `reduceWith(Callable,...)`: indicate star as a supplied value, operator name
- [ ] `repeat` + 1: indicate resubscription
- [ ] `repeatUntil`: indicate boolean supplier
- [ ] `replay` + 7: remove publish box
- [ ] `replay(Function)` + 7: rework diagram
- [ ] `retry()`: indicate infinte resubscription
- [ ] `retry(BiPredicate)`: indicate function decision on retry
- [ ] `retry(long)`: indicate retry count effect
- [ ] `retry(long, Predicate)`: indicate predicate effects
- [ ] `retry(Predicate)`: indicate predicate effects
- [ ] `retryUntil`: missing diagram
- [ ] `scan(R, ...)`: indicate initialValue as parameter
- [ ] `scan(Callable, ...)`: indicate initialValue is the result of a call
- [ ] `share`: indicate the source gets cancelled
- [ ] `singleElement`: operator name, should return Maybe
- [ ] `single`: operator name, should return Single
- [ ] `singleOrError`: combine cases into one box, add vertical case separators
- [ ] `skipUntil`: indicate until cancels the main source
- [ ] `sorted` + 1: missing diagram
- [ ] `startWith(Iterable)`: indicate iterable parameter, indicate subscription
- [ ] `startWith(Publisher)`: indicate subscription after the start element(s)
- [ ] `startWith(T)`: one start value, indicate subscription after the start element
- [ ] `startWithArray`: operator name, indicate subscription after the start element(s)
- [ ] `switchMapDelayError` + 1: operator name, indicate error is delayed
- [ ] `takeUntil(Predicate)`: indicate source is cancelled
- [ ] `takeUntil(Publisher)`: indicate source is cancelled
- [ ] `takeWhile`: indicate source is cancelled
- [ ] `to`: missing diagram
- [ ] `toList` + 1: should return Single
- [ ] `toList(Callable)`: should return Single, indicate custom collection
- [ ] `toMap` + 2: should return Single
- [ ] `toMultimap` + 3: should return Single
- [ ] `toObservable`: missing diagram
- [ ] `toSortedList` + 4: should return Single
- [ ] `unsubscribeOn`: missing diagram
- [ ] `withLatestFrom(s1, s2, ...)`: missing diagrams
- [ ] `withLatestFrom(Publisher[], ...)`: missing diagram
- [ ] `withLatestFrom(Iterable, ...)`: missing diagram

**Comment by ashishkrishnan** [comment]
Would like to contribute. Can you give me an heads-up?

**Comment by akarnokd** [comment]
Anything not checked is open for grabs. The list also hints about what should be done. The ones where only label needs to change are the easiest. Use any pixel painting software (I use Paint.NET). Post the png as comment here and I'll upload it to its proper place.

**Comment by ashishkrishnan** [comment]
Do the changes like for e.g `operator name` or `should return Single` be done on existing diagrams from the documentation? Can you please give me an example?

**Comment by akarnokd** [comment]
Example: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#fromArray-T...-

**Comment by skryvets** [comment]
What does number in "+ number" description mean?
