### ISSUE TITLE
Update wiki to reflect 4.x (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6132]
This is the overview of the suggested/planned changes to the Wiki. *Text in bold are for extra considerations/options*.

- [ ] [`Additional-Reading.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Additional-Reading.md): review links, add newer links to blogs and topics
- [ ] [`Alphabetical-List-of-Observable-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Alphabetical-List-of-Observable-Operators.md): remove non-standard, deleted & otherwise project-external operators, add newer operators, link to the categorized other `.md` files and sections in the wiki.
- [ ] *`Alphabetical-List-of-3rd-party-operators.md`: create page and list operators that used to be in RxJava and/or interesting enough, but available in 3rd party libraries, such as rxjava2-extras.*
- [ ] [`Async-Operators`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Async-Operators.md): review the operator set, point to RxJava2Extensions project, *add fancy descriptions like in #6131*.
- [ ] [`Backpressure`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Backpressure.md): update wording, remove unavailable operators, fix image links, make sure examples are in **Java**.
- [ ] *[`Backpressure-(2.0).md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Backpressure-(2.0).md): maybe review, should be okay as it has been recently added*
- [ ] [`Blocking-Observable-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Blocking-Observable-Operators.md): update to `blockingX` methods, *add fancy descriptions like in #6131*, existing operators only, fix image link
- [ ] [`Combining-Observables.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Combining-Observables.md): expand operator list (concat/eager/withLatestFrom missing?), *fancy like #6131*, link to RxJava2Extensions or explain join patterns here.
- [ ] [`Conditional-and-Boolean-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Conditional-and-Boolean-Operators.md): review operators, link/explain extensions ops, *fancy like #6131*
- [ ] [`Connectable-Observable-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Connectable-Observable-Operators.md): add newer operators, have examples in **Java**, fix image links
- [x] [`Creating-Observables.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Creating-Observables.md): add `generate`
- [x] [`Error-Handling-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Error-Handling-Operators.md): review set, *fancy like #6131*
- [ ] [`Error-Handling.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Error-Handling.md): review, only existing exceptions, include the error handling explanations from the [What's different](https://github.com/ReactiveX/RxJava/blob/3.x/docs/What's-different-in-2.0.md) page.
- [x] [`Filtering-Observables.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Filtering-Observables.md): review, remove nonexistent operators, *fancy like #6131*
- [ ] [`Getting-Started.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Getting-Started.md): fix versions and maven group ids, *remove troubleshooting section?*, *add getting started from Readme.md?*
- [ ] [`Home.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Home.md): RxJava project is no longer polyglot, link to the other RxYYY projects instead, review "sales pitch", review/expand libraries and check for true v2 version support, mention the v1 interop for the older libs
- [ ] [`How-To-Use-RxJava.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/How-To-Use-RxJava.md): *turn non-Java examples into Java*, use only Java examples, fix image links, review the create section
- [ ] [`How-to-Contribute.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/How-to-Contribute.md): needs extensive rewrite and detailing
- [ ] [`Implementing-Your-Own-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Implementing-Your-Own-Operators.md): needs extensive rewrite, somewhat redundant with `Writing-Operators-(2.0).md`.
- [ ] [`Implementing-custom-operators-(draft).md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Implementing-custom-operators-(draft).md): v1 only, unlist it and add banner **1.x content!**
- [ ] [`Mathematical-and-Aggregate-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Mathematical-and-Aggregate-Operators.md): review operator list, link to RxJava2Extensions, *fancy like #6131*, `concat` is not an aggregator 
- [ ] [`Observable-Utility-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Observable-Utility-Operators.md): review set, add new operators, *fancy like #6131*
- [ ] [`Observable.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Observable.md): pretty barebone, perhaps list all reactive types and their support interfaces with some descriptions
- [ ] [`Parallel-flows.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Parallel-flows.md): list parallel operators, `sequentialDelayError`, *fancy like #6131*, no longer experimental/beta
- [ ] [`Phantom-Operators.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Phantom-Operators.md): dumping ground for old/never relaized operators, remove or add warning about historical/museum content?
- [ ] [`Plugins.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Plugins.md): rewrite for `RxJavaPlugins` and related components
- [ ] [`Problem-Solving-Examples-in-RxJava.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Problem-Solving-Examples-in-RxJava.md): Fibonacci is not a relevant problem, not sure what problem examples could be listed here instead: how to wrap/bridge to existing technologies? How to get REST data into a listview?
- [ ] [`Reactive-Streams.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Reactive-Streams.md): remove v1 related details, wording: Java Flow has been shipped.
- [ ] [`Scheduler.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Scheduler.md): needs extensive expansion, also add system properties, *perhaps mention exotic schedulers in RxJava2Extensions*, *perhaps show how to write a scheduler*.
- [ ] [`String-Observables.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/String-Observables.md): the RxJava2Extensions only has a few string operators, link to them?, *fancy like #6131*
- [ ] [Subject.md](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Subject.md): needs extensive expansion: show the various subject types, their specific methods, examples.
- [ ] [`The-RxJava-Android-Module.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/The-RxJava-Android-Module.md): maybe just link to [RxAndroid](https://github.com/ReactiveX/RxAndroid#rxandroid-reactive-extensions-for-android) and remove the rest?
- [ ] [`Transforming-Observables.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Transforming-Observables.md): review and add new operators, *fancy like #6131*
- [X] [`What's-different-in-2.0.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/What's-different-in-2.0.md): fine
- [ ] [`Writing-operators-for-2.0.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/Writing-operators-for-2.0.md): expand: fusion topics, example operators
- [X] [`_Footer.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/_Footer.md): fine
- [x] [`_Sidebar.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/_Sidebar.md): not sure if this is actually displayed as there is the `_Sidebar.md.md` too. Sync the two.
- [x] [`_Sidebar.md.md`](https://github.com/ReactiveX/RxJava/blob/3.x/docs/_Sidebar.md.md): reorganize a bit (list categories under "all operators"), remove v1 references, move v2 pages up

**Comment by MohamedISoliman** [comment]
it's a great effort that you do guys in this repo, but I really find the docs is very difficult to reason about, specially when I need to learn a new operator .. so if it's updated with more links or examples it may really help to understand quickly.

**Comment by khkong** [comment]
@akarnokd 
An invalid link was found in the `Additional-Reading.md` file.
Can I merge request a partial update?

**Comment by MorrisLaw** [comment]
Maybe you can start picking up these tasks to get familiar with making PRs to this repo @ddunig2

**Comment by ddunig2** [comment]
@akarnokd  may I help contribute to this project?

**Comment by akarnokd** [comment]
@ddunig2 Sure.

**Comment by ddunig2** [comment]
@akarnokd im not sure if this issue is closed or not but I am fairly new to GitHub contribution. If this happens to be closed, whats a good first issue on this project?

**Comment by akarnokd** [comment]
Closed issues have a big red button indicating as such:

![image](https://user-images.githubusercontent.com/1269832/69789744-6ccdac00-11c1-11ea-8eae-d62a01c5b05b.png)

Otherwise, we don't have any good first issues at the moment. However, you could try and backport #6729 to the RxJava 2.x branch. Please consult a Git/Github tutorial if you don't know how to do things.

**Comment by ddunig2** [comment]
@akarnokd Im somewhat familiar with GitHub. By backport do you mean committing the fixes in #6729 to the 2.x branch?

**Comment by akarnokd** [comment]
You'd have to manually apply the changes in the source code of the 2.x branch as the files and locations do not match for an automatic backport.

**Comment by ddunig2** [comment]
@akarnokd I'm having trouble getting the project on my local machine without any errors. I forked and download it and wanted to make the changes on the eclipse IDE.  Any idea why that may be?

**Comment by akarnokd** [comment]
What are those errors? Which Eclipse version are you using?

**Comment by ddunig2** [comment]
@akarnokd Im using Eclipse-java 2019-09, java jdk13. The i just recloned it to check the issue and atm has no issue warning but when I run .\gradlew build, it fails







FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\lugdu\Desktop\GitHubContribution\RxJava\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\lugdu\Desktop\GitHubContribution\RxJava\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

  java.lang.IllegalArgumentException: Unsupported class file major version 57
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:254)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:192)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:172)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:128)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:59)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:46)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:81)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:72)
        at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:55)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:195)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:121)
        at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:912)
        at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1280)
        at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:252)
        at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:112)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:144)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:110)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:121)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:55)
        at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:88)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:128)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1099)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:54)
        at org.codehaus.groovy.control.StaticImportVisitor.visitClass(StaticImportVisitor.java:82)
        at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:717)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1095)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:649)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:627)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:604)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
        at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:133)

**Comment by akarnokd** [comment]
Install a Jdk 8 runtime and have Eclipse use it as a target:

![image](https://user-images.githubusercontent.com/1269832/69976838-f49d1880-1529-11ea-9a5a-212f12838522.png)

**Comment by ddunig2** [comment]
@akarnokd  of great, I don't notice any errors. Now, I am on the 3x branch, Im not too familiar with backporting, would you be able to give me a quick guide as to what happens from here? So you mentioned that i would have to manually change the source code in the 2x branch to match the 3x branch, Can I get a little more detail. Am I changing the whole code or am I looking at a specific package?

**Comment by akarnokd** [comment]
No.
1. Check out the 2.x branch
2. Create a new branch of of 2.x named `JavadocCleanup_1203`
3. Open the [changed files](https://github.com/ReactiveX/RxJava/pull/6729/files) of #6729 in a browser 
4. For each file, expand the sections until you see the method name. For the first entry, it is `public final Single<Long> count() {`
5. Locate this file and method in your IDE
6. Apply the changes you see on the web page: remove lines or add lines
7. Once done, make sure you have your own fork as remote in the Git repositories view under RxJava
8. Add a commit message and commit the changes, and then push to your fork.
9. Go to the PR page and wait for your branch to pop up to make a PR
10. Make a PR and fill in some explanation about what you've done.

**Comment by ddunig2** [comment]
@akarnokd thank you that was fairly descriptive. The first change I see is the removal of the @see #count but nothing in the method itself. Is that what you are referring to?
![pic](https://user-images.githubusercontent.com/36016544/70112974-52faf180-1625-11ea-9cf9-626c26528f39.JPG)

**Comment by ddunig2** [comment]
@akarnokd  I made a PR!

**Comment by VovaStelmashchuk** [comment]
Doc https://github.com/ReactiveX/RxJava/blob/2.x/docs/Filtering-Observables.md, Looks like up to date. Can you put checkmark?

**Comment by skywall** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#blockingstream
Currently defined as: 
[![Empty](https://camo.githubusercontent.com/3062cb1793ad53db80c889cb7ef5adb74094b793/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f6f66662e706e67)]() `Flowable`, [![Empty](https://camo.githubusercontent.com/3062cb1793ad53db80c889cb7ef5adb74094b793/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f6f66662e706e67)]() `Observable`, [![New](https://camo.githubusercontent.com/f38f3a0e59ab43c7d83ace6a715653caaccd1526/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f68616c662e706e67)]() `Maybe`, [![New](https://camo.githubusercontent.com/f38f3a0e59ab43c7d83ace6a715653caaccd1526/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f68616c662e706e67)]() `Single`, [![New](https://camo.githubusercontent.com/f38f3a0e59ab43c7d83ace6a715653caaccd1526/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f68616c662e706e67)]() `Completable`

But this should be:
[![New](https://camo.githubusercontent.com/f38f3a0e59ab43c7d83ace6a715653caaccd1526/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f68616c662e706e67)]() `Flowable`, [![New](https://camo.githubusercontent.com/f38f3a0e59ab43c7d83ace6a715653caaccd1526/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f68616c662e706e67)]() `Observable`, [![Empty](https://camo.githubusercontent.com/3062cb1793ad53db80c889cb7ef5adb74094b793/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f6f66662e706e67)]() `Maybe`, [![Empty](https://camo.githubusercontent.com/3062cb1793ad53db80c889cb7ef5adb74094b793/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f6f66662e706e67)]() `Single`, [![Empty](https://camo.githubusercontent.com/3062cb1793ad53db80c889cb7ef5adb74094b793/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f5265616374697665582f52784a6176612f696d616765732f636865636b6d61726b5f6f66662e706e67)]() `Completable`

**Comment by akarnokd** [comment]
@skywall Updated.

**Comment by mghildiy** [comment]
I would like to work on it.

**Comment by aleedy** [comment]
Looking to do a little a little contribution since I'm back working on a project using RxJava.  Would checking some of these off be the best place to start?

**Comment by akarnokd** [comment]
These two could use the restyling:
- https://github.com/ReactiveX/RxJava/blob/3.x/docs/Conditional-and-Boolean-Operators.md
- https://github.com/ReactiveX/RxJava/blob/3.x/docs/Observable-Utility-Operators.md

**Comment by evgenyponomarev** [comment]
I’ll update the 4.x Getting Started page’s dependency examples, Java baseline, and snapshot repository as a focused part of this checklist.
