### ISSUE TITLE
More operators/overloads

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#653]
Rx.NET 2.2.2
- [x] ~~Aggregate (PR #657)~~
  - `aggregate(seed, accumulator, resultselector)`
- [x] Average (PR #657, M)
  -  `average(Func1<T, Number> valueselector)`
- [x] Buffer (PR #733)
  - `Buffer(Observable<U> bufferBoundaries)`
- [x] ~~Create async~~
  - ~~`Create(Func1<Observer<R>, Task>)`~~
  - ~~`Create(Func1<Observer<R>, Task<Action>>)`~~
  - ~~`Create(Func1<Observer<R>, Task<IDisposable>>)`~~
  - ~~`Create(Func2<Observer<R>, CancellationToken, Task>)`~~
  - ~~`Create(Func2<Observer<R>, CancellationToken, Task<Action>>)`~~
  - ~~`Create(Func2<Observer<R>, CancellationToken, Task<IDisposable>>)`~~
- [x] Delay (PR #734)
  - `Delay(Func1<T, Observable<TDelay>>)`
  - `Delay(Func0<Observable<D1>> subscriptionDelay, Func1<T, Observable<D2>> itemDelay)`
- [x] ~~Empty (PR #654)~~
  - ~~`Empty(T witness)`~~
  - ~~`Empty(Scheduler, T witness)`~~
- [x] ~~Never (PR #654)~~
  - ~~`Never(T witness)`~~
- [x] Publish (PR #738)
  - `publish(Func1<Observable<TSource>, Observable<TResult>> sel)`
  - `publish(TSource initialValue)`
  - `publish(Func1<Observable<TSource>, Observable<TResult>> sel, TSource initialValue)`
- [x] PublishLast (PR #738)
  - `publishLast(Func1<Observable<TSource>, Observable<TResult>> sel)`
- [x] SelectMany (flatMap) (PR #736)
  - `SelectMany(Func1<T, Observable<U>> collection, Func2<T, U, R> resultSel)`
  - `SelectMany(Func1<T, Observable<R>> onNext, Func1<Exception, Observable<R>> onError, Func0<Observable<R>> onCompleted)`
  - `SelectMany(Func1<T, IEnumerable<R>>)`
  - `SelectMany(Func2<T, IEnumerable<U>>, Func2<T, U, R>)`
  - ~~----------------------------------~~
  - ~~`SelectMany(Func2<T, Integer, Observable<R>>)`~~
  - ~~`SelectMany(Func1<T, Task<R>>)`~~
  - ~~`SelectMany(Func2<T, Integer, Task<R>>)`~~
  - ~~`SelectMany(Func2<T, CancellationToken, Task<R>>)`~~
  - ~~`SelectMany(Func3<T, Integer, CancellationTokenk, Task<R>>)`~~
  - ~~`SelectMany(Func1<T, Integer, Observable<U>> collection, Func4<T, Integer,  U, Integr, R> resultSel)`~~
  - ~~`SelectMany(Func1<T, Task<U>>, Func2<T, U, R>)`~~
  - ~~`SelectMany(Func2<T, Integer, Task<U>>, Func2<T, Integer, U, R>)`~~
  - ~~`SelectMany(Func2<T, CT, Task<U>>, Func2<T, U, R>)`~~
  - ~~`SelectMany(Func3<T, Integer, CT, Task<U>>, Func2<T, Integer, U, R>)`~~
  - ~~`SelectMany(Func2<T, Integer, Observable<R>> onNext, Func1<Exception, Observable<R>> onError, Func0<Observable<R>> onCompleted)`~~
  - ~~`SelectMany(Func2<T, Integer, IEnumerable<R>>)`~~
  - ~~`SelectMany(Func3<T, Integer, IEnumerable<U>>, Func4<T, Integer, U, Integer, R>)`~~
- [x] Skip (PR #655, M)
  - `Skip(Timespan)`
  - `Skip(Timespan, Scheduler)`
- [x] SkipLast  (PR #655, M)
  - `SkipLast(Timespan)`
  - `SkipLast(Timespan, Scheduler)`
- [x] Sum (PR #657 M)
  - `sum(Func1<T, Number> valueselector)`
- [x] Take  (PR #655, M)
  - `Take(Timespan)`
  - `Take(Timespan, Scheduler)`
- [x] TakeLast  (PR #655, M)
  - `TakeLast(Timespan)`
  - `TakeLast(Timespan, Scheduler)`
  - `TakeLast(Timespan, Scheduler duration, Scheduler drain)`
- [x] Throttle (debounce) (PR #739)
  - `Throttle(Func1<T, Observable<Void>>)`
- [x] Timeout (PR #740)
  - `Timeout(Func1<T, Observable<Void>>)`
  - `Timeout(Func1<T, Observable<Void>>, Observable<T> other)`
  - `Timeout(Func0<Observable<Void>>, Func1<T, Observable<Void>>)`
  - `Timeout(Func0<Observable<Void>>, Func1<T, Observable<Void>>, Observable<T> other)`
- [x] ~~Throw (error) (PR #654)~~
  - ~~`error(Throwable t, T witness)`~~
  - ~~`error(Throwable t, Scheduler, T witness)`~~
- [x] ~~Using async~~
  - ~~`Using(Func1<CancellationToken, Task<TResource>>, Func2<TResource, CancellationToken, Task<Observable<T>>>)`~~
- [x] ~~Where~~
  - ~~`Where(Func2<T, Integer, Boolean>)`~~
- [x] Window (PR #735)
  - `Window(Observable<U> windowBoundaries)`
- [x] Zip (PR #741)
  - ~~`Zip(IEnumerable<Observable<S>> sources, Func1<IList<S>, R> selector)`~~ (already have with FuncN)
  - `Zip(Iterable<U> other, Func2<T, U, R> result)` (instance method)
  - `Zip(Observable<U> other, Func2<T, U, R> result)` (instance method)

Potential Java specific operators/overloads:
- [ ] `just(Func0<R> factory)` return the value of the factory for the subscriber.
- [x] ~~`lock(Lock lock)` or `synchronize(Lock lock)` to support j.u.c.Locks for synchronization.~~
- [x] ~~Using with java.io.Closeable~~
  - ~~`using(Func0<C>, Func1<C, Observable<T>>)`~~
  - ~~`usingFuture(Func1<BooleanSubscription, Future<C>>, Func2<C, BooleanSubscription, Future<Observable<T>>>)`~~
