### ISSUE TITLE
3.x: [Java 8] Add operators supporting the newer platform [tracking issue]

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6776]
This issue tracks the new, Java 8-related operators to be implemented.

- [x] `Flowable.fromOptional`
- [x] `Flowable.fromStream`
- [x] `Flowable.fromCompletionStage`
- [x] `Flowable.mapOptional`
- [x] `Flowable.collect(Collector)`
- [x] `Flowable.firstStage`
- [x] `Flowable.singleStage`
- [x] `Flowable.lastStage`
- [x] `Flowable.firstOrErrorStage`
- [x] `Flowable.singleOrErrorStage`
- [x] `Flowable.lastOrErrorStage`
- [x] `Flowable.blockingStream` + 1
- [x] `Flowable.flatMapStream` + 1
- [x] `Flowable.concatMapStream` + 1
-----
- [x] `Observable.fromOptional`
- [x] `Observable.fromStream`
- [x] `Observable.fromCompletionStage`
- [x] `Observable.mapOptional`
- [x] `Observable.collect(Collector)`
- [x] `Observable.firstStage`
- [x] `Observable.singleStage`
- [x] `Observable.lastStage`
- [x] `Observable.firstOrErrorStage`
- [x] `Observable.singleOrErrorStage`
- [x] `Observable.lastOrErrorStage`
- [x] `Observable.blockingStream` + 1
- [x] `Observable.flatMapStream`
- [x] `Observable.concatMapStream`
-----
- [x] `Maybe.fromOptional`
- [x] `Maybe.fromCompletionStage`
- [x] `Maybe.mapOptional`
- [x] `Maybe.toCompletionStage()` + 1
- [x] `Maybe.flattenStreamAsFlowable`
- [x] `Maybe.flattenStreamAsObservable`
-----
- [x] `Single.fromCompletionStage`
- [x] `Single.mapOptional` returns `Maybe<T>`
- [x] `Single.toCompletionStage()`
- [x] `Single.flattenStreamAsFlowable`
- [x] `Single.flattenStreamAsObservable`
-----
- [x] `Completable.fromCompletionStage`
- [x] `Completable.toCompletionStage`
-----
- [x] `ParallelFlowable.mapOptional`
- [x] `ParallelFlowable.flatMapStream`
- [x] `ParallelFlowable.collect(Collector)` returns `Flowable`

**Comment by JakeWharton** [comment]
~How about eliminating the plural sibling classes and moving their static factories onto the main class? For example, the factories on `Disposables` can be moved to `Disposable`.~

Nevermind this isn't operator-related. I'll just send a PR!

**Comment by akarnokd** [comment]
Will Android desugaring be able to work with that?

**Comment by JakeWharton** [comment]
Yep. Supported since AGP 3.2 well over a year now.

**Comment by akarnokd** [comment]
The previously `???` marked entries will be better implemented externally for now (RxJavaExtensions).
