### ISSUE TITLE
3.x: Missing operators (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6852]
https://github.com/ReactiveX/RxJava/wiki/Operator-Matrix

https://github.com/ReactiveX/RxJava/wiki/Operator-Matrix#under-development

Operators present in some but not other classes (when they make sense there too):

- [x] `Completable.concatArrayDelayError`
- [x] `Completable.blockingSubscribe`
- [x] `Completable.doOnLifecycle`
- [x] `Completable.onErrorResumeWith`
- [x] `Completable.onErrorReturn`
- [x] `Completable.onErrorReturnItem`
- [x] `Completable.retryUntil`
- [x] `Completable.safeSubscribe`
- [x] `Completable.sequenceEqual`
- [x] `Completable.startWith` (`MaybeSource`, `SingleSource`)
- [x] `Completable.switchOnNext`
- [x] `Completable.switchOnNextDelayError`
- [x] `Completable.toFuture`
- [x] `Maybe.blockingSubscribe`
- [x] `Maybe.concatArrayEagerDelayError`
- [x] `Maybe.concatMapCompletable`
- [x] `Maybe.concatMapSingle`
- [x] `Maybe.dematerialize`
- [x] `Maybe.fromObservable`
- [x] `Maybe.doOnLifecycle`
- [x] `Maybe.fromPublisher`
- [x] `Maybe.safeSubscribe`
- [x] `Maybe.startWith` 
- [x] `Maybe.timeInterval`
- [x] `Maybe.timestamp`
- [x] `Maybe.toFuture`
- [x] `Maybe.switchOnNext`
- [x] `Maybe.switchOnNextDelayError`
- [x] `Single.blockingSubscribe`
- [x] `Single.concatArrayDelayError`
- [x] `Single.concatArrayEagerDelayError`
- [x] `Single.concatDelayError`
- [x] `Single.concatMap`
- [x] `Single.concatMapCompletable`
- [x] `Single.concatMapMaybe`
- [x] `Single.doOnLifecycle`
- [x] `Single.fromMaybe`
- [x] `Single.mergeArray`
- [x] `Single.mergeArrayDelayError`
- [x] `Single.ofType`
- [x] `Single.onErrorComplete`
- [x] `Single.retryUntil`
- [x] `Single.safeSubscribe`
- [x] `Single.sequenceEqual` (rename `equals`)
- [x] `Single.startWith` 
- [x] `Single.timeInterval`
- [x] `Single.timestamp`
- [x] `Single.switchOnNext`
- [x] `Single.switchOnNextDelayError`
- [x] `Flowable.fromAction`
- [x] `Flowable.fromCompletable`
- [x] `Flowable.fromMaybe`
- [x] `Flowable.fromObservable`
- [x] `Flowable.fromRunnable`
- [x] `Flowable.fromSingle`
- [x] `Flowable.onErrorComplete`
- [x] `Flowable.startWith` (`MaybeSource`, `SingleSource`, `CompletableSource`)
- [x] `Observable.fromAction`
- [x] `Observable.fromCompletable`
- [x] `Observable.fromMaybe`
- [x] `Observable.fromRunnable`
- [x] `Observable.fromSingle`
- [x] `Observable.onErrorComplete`
- [x] `Observable.startWith` (`MaybeSource`, `SingleSource`, `CompletableSource`)

**Comment by souraexx** [comment]
Can I work on it?

**Comment by akarnokd** [comment]
@souraexx Sure, pick one. I'm currently working on all `onErrorComplete`s.
